org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true

project.version=1.0.0
main.class=org.RestApp

dir.src.java=src/main/java
dir.src.resources=src/main/resources
dir.src.tests=src/test/java
dir.build=build
dir.build.classes=build/classes/java/main
dir.build.libs=build/libs
dir.build.docs=build/docs/javadoc

git.tracked.classes=src/main/java/org/